# Generated by Django 4.2.7 on 2023-12-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_collections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
