# Generated by Django 4.2.7 on 2023-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_rename_collections_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='pokemon_cards',
            field=models.ManyToManyField(to='pokeapp.pokemoncard'),
        ),
        migrations.AddField(
            model_name='collection',
            name='trainers',
            field=models.ManyToManyField(to='pokeapp.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='abilities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='weakness',
            field=models.CharField(max_length=100),
        ),
    ]
