# Generated by Django 4.2.7 on 2023-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_collection_pokemon_cards_collection_trainers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
