# Generated by Django 4.2.7 on 2023-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0005_pokemoncard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
