# Generated by Django 4.2.7 on 2023-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0008_remove_collection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
