# Generated by Django 4.2.7 on 2023-12-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0010_trainer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='trainers',
            new_name='trainer',
        ),
    ]
