# Generated by Django 4.2.7 on 2023-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0011_rename_trainers_collection_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='card',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='trainer',
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(blank=True, to='pokeapp.pokemoncard'),
        ),
        migrations.AddField(
            model_name='collection',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='pokeapp.trainer'),
        ),
    ]
